FROM rustlang/rust:nightly-alpine AS builder
USER root

# Install build dependencies
RUN apk update && apk add --no-cache \
    musl-dev \
    gcc \
    libc-dev \
    pkgconfig \
    openssl-dev \
    git \
    protobuf-dev

WORKDIR /microservice-project

# Copy the entire project
COPY . .

# Build the application
RUN cargo build --release --bin auth

# We do not need the Rust toolchain to run the binary!
FROM debian:buster-slim AS runtime
WORKDIR /microservice-project
COPY --from=builder /microservice-project/target/release/auth /usr/local/bin
ENTRYPOINT ["/usr/local/bin/auth"]