FROM rustlang/rust:nightly-alpine AS builder
USER root

# Actualizar repositorios e instalar todas las dependencias necesarias
RUN apk update && apk add --no-cache \
    musl-dev \
    gcc \
    libc-dev \
    pkgconfig \
    openssl-dev \
    git \
    protobuf-dev

WORKDIR /microservice-project

# Copy the entire project
COPY . .

# Build the application
RUN cargo build --release --bin health-check

# We do not need the Rust toolchain to run the binary!
FROM debian:buster-slim AS runtime
WORKDIR /microservice-project
COPY --from=builder /microservice-project/target/release/health-check /usr/local/bin
ENTRYPOINT ["/usr/local/bin/health-check"]